LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/Controllers/SharedController.cs
using HtmlAgilityPack;
using LigaAlgorytmicznaSPOJNetCore.Data;
using LigaAlgorytmicznaSPOJNetCore.Database.Models;
using LigaAlgorytmicznaSPOJNetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace LigaAlgorytmicznaSPOJNetCore.Controllers
{
    
    public class DetailProblem
    {
        public string Text { get; set; }
        public string Input { get; set; }
        public string Output { get; set; }

    }

    public class SharedController : Controller
    {
        private readonly ApplicationDbContext _dbContext = new ApplicationDbContext();

        public string GetDetailProblemInfo(string link)
        {
            var url = "http://" + link;
            var web = new HtmlWeb();
            var doc = web.Load(url);
            var text = getBetween(doc.ParsedText, "<div id=\"problem-body\">", "</div>");
            return text;
        }
        public ActionResult DetailProblems(string link)
        {
            var info = GetDetailProblemInfo(link);
            return View(info);
        }
        public static string getBetween(string strSource, string strStart, string strEnd)
        {
            int Start, End;
            if (strSource.Contains(strStart) && strSource.Contains(strEnd))
            {
                Start = strSource.IndexOf(strStart, 0) + strStart.Length;
                End = strSource.IndexOf(strEnd, Start);
                return strSource.Substring(Start, End - Start);
            }
            else
            {
                return "";
            }
        }

        public static List<Problem> GetClassicalProblems()
        {
            var url = "http://www.spoj.com/problems/classical/";
            var web = new HtmlWeb();
            var doc = web.Load(url);
            var list = new List<Problem>();
            foreach (var row in doc.DocumentNode.SelectNodes("//table//tbody"))
            {
                HtmlNodeCollection cells = row.SelectNodes("tr");
                if (cells != null)
                {
                    foreach (HtmlNode cell in cells)
                    {
                        HtmlNodeCollection kom = cell.SelectNodes("td");
                        if (kom != null)
                        {
                            var problem = new Problem();

                            int i = 0;

                            foreach (HtmlNode item in kom)
                            {
                                if (i == 0)
                                { problem.Id = item.InnerText.Trim(); }
                                else if (i == 1)
                                {
                                    problem.Name = item.InnerText.Trim();
                                    problem.Link = "www.spoj.com" + getBetween(item.InnerHtml, "<a href=\"", "\">");


                                }
                                else if (i == 2)
                                { problem.Quality = item.InnerText.Trim(); }
                                else if (i == 3)
                                { problem.Users = item.InnerText.Trim(); }
                                else if (i == 4)
                                { problem.Acc = item.InnerText.Trim(); }
                                else if (i == 5)
                                {
                                    problem.Difficulty = item.InnerText.Trim();
                                    list.Add(problem);
                                    i = -1;
                                }

                                i++;
                            }
                        }
                    }
                }
            }

            return list;
        }
        public static List<Problem> PolishProblems()
        {

            //        var url = "http://www.spoj.com/problems/classical/";
            var url = "https://pl.spoj.com/problems/latwe/";
            var web = new HtmlWeb();
            var doc = web.Load(url);
            var list = new List<Problem>();
            foreach (var row in doc.DocumentNode.SelectNodes(@"//*[@id=""content""]/table[3]"))
            {
             var   a = row;
                HtmlNodeCollection cells = row.SelectNodes("tr");
                if (cells != null)
                {
                    foreach (HtmlNode cell in cells)
                    {
                        HtmlNodeCollection kom = cell.SelectNodes("td");
                        if (kom != null)
                        {
                            var problem = new Problem();

                            int i = 0;

                            foreach (HtmlNode item in kom)
                            {
                                if (i == 0)
                                { problem.Id = item.InnerText.Trim(); }
                                else if (i == 1)
                                {
                                    problem.Name = item.InnerText.Trim().Replace("&nbsp;\n&nbsp;", "");
                                    problem.Link = "www.pl.spoj.com/" + getBetween(item.InnerHtml, "<a href=\"", "\">");
                                }
                                else if (i == null)
                                { problem.Quality = item.InnerText.Trim(); }
                                else if (i == 3)
                                { problem.Users = item.InnerText.Trim(); }
                                else if (i == 4)
                                {
                                    problem.Acc = item.InnerText.Trim();
                                    list.Add(problem);
                                }
                                else if (i == 5)
                                {
                                    problem.Difficulty = item.InnerText.Trim();
                                    list.Add(problem);
                                    i = -1;
                                }

                                i++;
                            }
                        }
                    }
                }
            }

            return list;
        }
        public ActionResult ClassicalProblems()
        {
            var classicalProblems = GetClassicalProblems();

            return View(classicalProblems);
        }
        public ActionResult GetPolishProblems()
        {
            var classicalProblems = PolishProblems();
            return View("ClassicalProblems",classicalProblems);
        }
        
        public void Ocen(Guid nameofproblem)
        {
            var listUsers = new List<ApplicationUser>();
            listUsers = _dbContext.Users.Where(x => x.isConfirmed).ToList();
            var exercise = _dbContext.Exercises.FirstOrDefault(x => x.Id == nameofproblem);
            var listStudentWithMark = new List<StudentAndMark>();
            foreach (var item in listUsers)
            {
                var studentWithMark = new StudentAndMark();
                var mark = new Mark();
                mark = _dbContext.Marks.FirstOrDefault(x => x.Id_Person == item.Id && x.Id_Exercise == nameofproblem);
                studentWithMark.User = item;
                studentWithMark.Mark = mark;
                studentWithMark.NameExcercise = exercise.Name;
                studentWithMark.IdExercise = nameofproblem;

                listStudentWithMark.Add(studentWithMark);
            }
      //      listStudentWithMark.OrderByDescending(x => x.)
            foreach (var student in listStudentWithMark)
            {
      



            }


        }
   


    }
  

    public class UserRanking
    {
        public ApplicationUser User { get; set; }
        public List<Mark> Marks { get; set; }
        public int Score { get; set; }
        public UserRanking(ApplicationUser item, List<Mark> marks)
        {
            this.User = item;
            this.Marks = marks;
            Score = Marks.Sum(x => x.Score);
        }

   
    }
}

LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/Views/Shared/ClassicalProblems.cshtml
@using System.ComponentModel.DataAnnotations
@model System.Collections.Generic.List<LigaAlgorytmicznaSPOJNetCore.Models.Problem>

@{
    ViewBag.Title = "Program";
    Layout = "~/Views/Shared/MenuLayout.cshtml";
}
@if (User.Identity.GetUserisConfirmed())
{

<h2>Lista Problemów</h2>
<div>
    <a href="ClassicalProblems" target="_blank">Angielski Spoj</a>
    <a href="GetPolishProblems" target="_blank">Polski Spoj</a>
</div>
<div class="container">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nazwa</th>
                <th>Jakość</th>
                <th>Trudność</th>
                <th>Acc</th>
                <th>Link</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>

            @foreach (var problem in Model)
            {
                <tr>
                    <td>@problem.Id</td>

                    <td> <a href="https://@problem.Link" target="_blank">@problem.Name</a></td>


                    @*<td>@Html.ActionLink(problem.Name, "GetDetailProblemInfo", "Shared", new { link = problem.Link }, null)</td>*@
                    <td>@problem.Quality</td>
                    <td>@problem.Difficulty</td>
                    <td>@problem.Acc</td>
                    <td>@problem.Link</td>


                    <td>

                        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#@problem.Id">
                            <span>+</span>
                        </button>


                    </td>
                </tr>
                using (@Html.BeginForm("AddExerciseToDb", "Administrator", FormMethod.Post))
                {
                    <div class="modal fade" id="@problem.Id" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">



                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h3 class="modal-title">Dodawanie zadania do wykonania</h3>
                                </div>
                                @Html.TextBox("IdExercise", problem.Id, new { @hidden = "hidden" })
                                @Html.TextBox("Name", problem.Link, new { @hidden = "hidden" })
                                <div class="form-group">
                                    <h4>Maksymalna ilość pkt za zadanie</h4>
                                    <p></p>
                                    @Html.TextBox("Score", "", new { placeholder = "Maksymalna ilość pkt do uzyskania", @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <h3>Do kiedy wykonac</h3>
                                    @Html.TextBox("DateToDo", "", new { placeholder = "Data", type = "date", @class = "form-control" })





                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Zamknij</button>
                                <button type="submit" class="btn btn-default" value="Dodaj to zadanie">Dodaj Zadanie</button>

                            </div>




                        </div>
                    </div>
                }
            }


        </tbody>

    </table>
</div>
}

LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/Views/Shared/MenuLayout.cshtml
@using LigaAlgorytmicznaSPOJNetCore.Models
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="menu">
    @if (User.IsInRole("Student"))
    {
       if (User.Identity.GetUserisConfirmed())
        {

        
        <a href="@Url.Action("ToDo", "Student")" id="one-menu">To Do<span class="glyphicon glyphicon-envelope"></span></a>
        <a href="@Url.Action("GetViewMarkWithExercise", "Student")" id="two-menu">Ocenione <span class="glyphicon glyphicon-asterisk    "></span></a>
        @*<a href="@Url.Action("ProblemsResolve", "Student")" id="three-menu">Rozwiązane <span class="glyphicon glyphicon-saved"></span></a>*@
        <a href="@Url.Action("RankingView", "Student")" id="three-menu">Ranking <span class="glyphicon glyphicon-signal"></span></a>

        @*<a href="@Url.Action("ResultProblem", "Student")" id="three-menu">WynikiProblemu <span class="glyphicon glyphicon-pencil"></span></a>*@
        @*<a href="@Url.Action("ClassicalProblems", "Shared")" id="six-menu">Zadania <span class="glyphicon glyphicon-search"></span></a>*@
        <a href="@Url.Action("PersonalData", "Student")" id="four-menu">Moje dane <span class="glyphicon glyphicon-user"></span></a>
        }
    }
    else if (User.IsInRole("Administrator"))
    {
        <a href="@Url.Action("ShowExercisesToDo", "Administrator")" id="one-menu">Zadania <span class="glyphicon glyphicon-pencil"></span></a>
        <a href="@Url.Action("ShowPersons", "Administrator")" id="two-menu">Członkowie <span class="glyphicon glyphicon-user"></span></a>
        @*<a href="@Url.Action("ClassicalProblems", "Shared")" id="three-menu">SPOJ <span class=" glyphicon glyphicon-search"></span></a>*@
        <a href="@Url.Action("RankingView", "Administrator")" id="three-menu">Ranking<span class="glyphicon glyphicon glyphicon-signal"></span></a>
        <a href="@Url.Action("ManagePoints", "Administrator")" id="four-menu">Punktacja<span class="glyphicon glyphicon glyphicon-signal"></span></a>
        <a href="@Url.Action("PersonalData", "Administrator")" id="five-menu">Moje Dane<span class="glyphicon glyphicon glyphicon-signal"></span></a>

    }

    @using (Html.BeginForm("LogOff", "Home", FormMethod.Post, new { id = "logout-menu" }))
    {
        @Html.AntiForgeryToken()
        <a href="javascript:document.getElementById('logout-menu').submit()" id="logout-menu">Wyloguj <span class="glyphicon glyphicon-off"></span></a>
    }
</div>
<div class="panel main-panel">
    <div class="panel-body">
        <div class="row">
            @RenderBody()
            <div class="footer">
                <p>Zalogowano: @User.Identity.GetUserFirstname() <span class="glyphicon glyphicon-globe"></span> @DateTime.Now.ToString("dddd, MM.dd.yyyy")</p>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @RenderSection("Scripts", required: false)

}

LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/Views/Shared/PersonalDataLayout.cshtml
@model LigaAlgorytmicznaSPOJNetCore.Models.ApplicationUser
@{
    ViewBag.Title = "Moje dane";
    Layout = "~/Views/Shared/MenuLayout.cshtml";

    var role = "Student";

    if (User.IsInRole("Student"))
    {
        role = "Student";

    }
    else if (User.IsInRole("Administrator"))
    {
        role = "Administrator";
    }
}

<div class="col-md-12 col-sm-12 col-xs-12">
    <h2>Moje dane</h2>
    <p>Imię: @Model.FirstName</p>
    <p>Nazwisko: @Model.LastName</p>
    @if (Model.Gender == "Man")
    {
        <p>Płeć: Mężczyzna</p>
    }
    else
    {
        <p>Płeć: Kobieta</p>
    }
    <br />

    <p>Nr Albumu: @Model.AlbumNumber</p>
    <p>Data urodzenia: @Model.BirthDate.Value.ToString("dd.MM.yyyy")</p>
    <br />
    <p>Telefon: @Model.PhoneNumber</p>
    <p>E-mail: @Model.Email</p>
</div>

<div class="col-md-4 col-sm-6 col-xs-12">
    <input class="btn btn-primary btn-lg btn-block" type="button" data-toggle="modal" data-target="#newMessageModal" value="Edytuj dane" />
</div>

<div class="col-md-4 col-sm-6 col-xs-12">
    <input class="btn btn-primary btn-lg btn-block" type="button" data-toggle="modal" data-target="#MessageModal" value="Zmień hasło" />
</div>
@using (Html.BeginForm("ChangePassword", "Home", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="modal fade" id="MessageModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <h1>Zmień hasło</h1>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="form-group">
                            @Html.TextBox("Haslo","", new { placeholder = "Haslo", type = "text", maxlength = "12", @class = "form-control", required = "required" })
                            @Html.TextBox("NoweHaslo","", new { type = "text", placeholder = "NoweHaslo", @class = "form-control", required = "required" })
                        </div>

                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <input class="btn btn-primary btn-lg btn-block" type="submit" value="Zmień" />
                            <input class="btn btn-primary btn-lg btn-block" type="button" value="Zamknij" data-dismiss="modal" />

                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

}

@using (Html.BeginForm("EditPersonalData", role, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="modal fade" id="newMessageModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <h1>Edycja danych</h1>
                    <div class="col-md-12 col-sm-12 col-xs-12">
                       <div class="form-group">
                            @Html.TextBoxFor(m => m.PhoneNumber, new { placeholder = "Telefon", type = "text", maxlength = "12", @class = "form-control", required = "required" })
                            @Html.TextBoxFor(m => m.Email, new { type = "email", placeholder = "E-mail", @class = "form-control", required = "required" })
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <input class="btn btn-primary btn-lg btn-block" type="submit" value="Zmień" />
                            <input class="btn btn-primary btn-lg btn-block" type="button" value="Zamknij" data-dismiss="modal" />
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>

}

@RenderBody()

LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/LigaAlgorytmicznaSPOJNetCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LigaAlgorytmicznaSPOJNetCore</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
@*<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown link
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
        @*<partial name="_LoginPartial" />*@
    @*</div>*@
@*</nav>*@

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; 2018 - LigaAlgorytmicznaSPOJNetCore</p>*@
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>